refactor to use partial initial values
bcgov/myhealthBC-symptom-checker pull request #30
Opened 2022-01-26 19:05 UTC by sunghwan-park-fw

2022-01-26 19:11 UTC, sunghwan-park-fw commented
@vyasworks 
I don't understand this pr-check failure. This branch is based on 'happ-441_severity-of-cough' branch and it has passed pr-check.

2022-01-26 20:53 UTC, vyasworks commented
> @vyasworks I don't understand this pr-check failure. This branch is based on 'happ-441_severity-of-cough' branch and it has passed pr-check.

you can open the action and see it says 

```src/forms/SymptomChecker.tsx
  Line 6:10:  'Values' is defined but never used  @typescript-eslint/no-unused-vars```

2022-01-26 23:41 UTC, hitankar-freshworks requested changes
Please take a look at my comment

2022-01-26 23:41 UTC, hitankar-freshworks commented on apps/web/src/types/Symptoms.ts
> +  fever!: Severity;
why not? by default it would be false

```suggestion
  fever!: Severity | boolean = false;
```

2022-01-27 00:11 UTC, hitankar-freshworks approved these changes

2022-01-27 00:35 UTC, merged